Add proper checking for requirements in launcher

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -17,37 +17,49 @@ function ask_continue(){
     esac
 }
 
+function request_install_dependencies() {
+    # Ask for confirmation
+
+    echo -e "${C_BOLD_HEADER}First we need your approval to update ...${C_END}"
+
+    echo '$ apt-get -y -qq update && apt-get -y -qq upgrade'
+
+    echo -e "${C_BOLD_HEADER}... and to install these required dependencies:${C_END}"
+
+    echo '$ apt-get -y -qq install python3 python3-pip'
+
+    echo '$ pip3 -qq install click ruamel.yaml schema progressbar'
+
+    echo -e "${C_BOLD_HEADER}Then we will perform your setup instructions.${C_END}"
+
+    ask_continue
+
+    # Update and install requirements
+
+    echo -e "${C_BOLD_HEADER}This may take some time. Please wait.${C_END}"
+
+    apt-get -y -qq update && apt-get -y -qq upgrade
+
+    apt-get -y -qq install python3 python3-pip
+
+    pip3 -qq install click ruamel.yaml schema progressbar
+
+    echo -e "${C_BOLD_SUCCESS}✓ Requirements installed!${C_END}"
+}
+
 # Require root access
 if [ "$UID" -ne 0 ]; then
     exec sudo "$0" "$@"
 fi
 
-# Ask for confirmation
+# Check for requirements
+check_command='import click, ruamel.yaml, schema, progressbar'
+
 echo -e "${C_BOLD_SUCCESS}🚀 Hey ${SUDO_USER}, let's setup your system!${C_END}"
 
-echo -e "${C_BOLD_HEADER}First we need your approval to update ...${C_END}"
-
-echo '$ apt-get -y -q update && apt-get -y -q upgrade'
-
-echo -e "${C_BOLD_HEADER}... and to install these required dependencies:${C_END}"
-
-echo '$ apt-get -y -q install python3 python3-pip'
-
-echo '$ pip3 install click pyyaml schema'
-
-echo -e "${C_BOLD_HEADER}Then we will perform your setup instructions.${C_END}"
-
-ask_continue
-
-# Update and install requirements
-
-echo -e "${C_BOLD_HEADER}This may take some time. Please wait.${C_END}"
-
-apt-get -y -q update && apt-get -y -q upgrade
-
-apt-get -y -q install python3 python3-pip
-
-pip3 install click ruamel.yaml schema
+if ! python3 -c "${check_command}" &> /dev/null; then
+    request_install_dependencies
+fi
 
 # Perform setup
 
